version: '3.8'

# Development Docker Compose - Only for backend and frontend services
# Uses local PostgreSQL and Redis installations

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: events_backend_dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/events_registration_db
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      REDIS_URL: redis://host.docker.internal:6379
      NODE_ENV: development
      PORT: 3001
      GRAPHQL_PLAYGROUND: true
      GRAPHQL_INTROSPECTION: true
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - events_network
    command: pnpm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: events_frontend_dev
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:3001/graphql
      NEXT_PUBLIC_GRAPHQL_WS_URL: ws://localhost:3001/graphql
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - events_network
    command: pnpm run dev

networks:
  events_network:
    driver: bridge
